language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: o33iIQMkpWcFY/2AxxOGPl7DpLJWHLF9JRvtrRFTsSQXJmAB6PAU/JVQu2u5dMeQPkmiTv4At9GIKCGnaY/FsLF8XkoKtm2NkZ3cIGIdGNwhi7MoAZ8L/ivGsXSj1tGtIOzXt08eElr/d0kEMPjtW3YLjVBhZB3rHjvdg32F+N0C3zWOvY68cpGJhOtZGsaakHIRFYpmSil6qEZDCp23eo+itYHTgrPVKuR6o4FcdXk+KuQZEUu+rcxNjNRELSbkDetM5fECq04RCASQnMGtVOnaoZRORwADV/EpwOEpoBKvhNp7m2qu61bH4yqj96GtGBGzp1/YSfeCtRdDa9BXklsemDMDEWKgDhndqCOuZ3V7DTKxUQ+js3kH3Ah7ODZO9divZVOtpxWKyhf52MsQXm2b/mpoDQtexz3nyOWGdGHXJWk7Q1L2PiCTbco1lsFDRnOYj48oEgRgD9D6WqhzyTEUAngWuN4P646sDdeLUnIE/8LKfdh3QniT1OwZX5gNRG76n0qhUuY+iQS6H4ur56FZXXNhWSBlcy8ef7vKmZ91W0jD6+yat/HPSA0dnZBXvnYSDz7+5I5S9fPiy/dpr2eSR71q4qIWKUsYbcge3vodLaxAiMIsvBhMSaX9aSEfol1H5XTveVXQtJglvlzzyCUj00D0rGxPcgc/bR8KYO0=
  app: https://mighty-savannah-43632.herokuapp.com/ | https://git.heroku.com/mighty-savannah-43632.git
  on:
    repo: keyth202/blog-api
before_script: chmod 0777 ./node_modules/mocha/bin/mocha
